ene. 09, 2024 8:12:06 P. M. utils.ErrorLogger log
SEVERE: error severo!!!
ene. 09, 2024 8:17:21 P. M. utils.LoggerError log
SEVERE: [Ljava.lang.StackTraceElement;@5acf9800
/ by zero
ene. 09, 2024 8:21:32 P. M. utils.LoggerError log
SEVERE: [utils.Test.main(Test.java:86)]/ by zero


ene. 09, 2024 8:30:04 P. M. utils.LoggerError log
SEVERE: Stack: [utils.Test.main(Test.java:86)]Error: / by zero
ene. 09, 2024 8:31:01 P. M. utils.LoggerError log
SEVERE: Stack: [utils.Test.main(Test.java:86)] Error: / by zero

ene. 09, 2024 8:31:02 P. M. utils.LoggerError log
SEVERE: Stack: [utils.Test.main(Test.java:86)] Error: / by zero

ene. 29, 2024 11:06:00 P. M. utils.LoggerError log
SEVERE: Stack: [com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120), com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122), com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046), com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031), Data.DataEjemplar.updateEjemplaresToAlquilados(DataEjemplar.java:279), utils.Test.main(Test.java:80)] Error: Unknown column 'id' in 'where clause'

ene. 29, 2024 11:06:32 P. M. utils.LoggerError log
SEVERE: Stack: [com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120), com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122), com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046), com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031), Data.DataEjemplar.updateEjemplaresToAlquilados(DataEjemplar.java:279), utils.Test.main(Test.java:80)] Error: Unknown column 'available' in 'field list'

ene. 29, 2024 11:06:49 P. M. utils.LoggerError log
SEVERE: Stack: [com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104), com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046), com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031), Data.DataEjemplar.updateEjemplaresToAlquilados(DataEjemplar.java:279), utils.Test.main(Test.java:80)] Error: Data truncation: Truncated incorrect DOUBLE value: '[4, 6]'

feb. 04, 2024 5:36:48 P. M. utils.LoggerError log
SEVERE: Stack: [com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120), com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122), com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046), com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371), com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031), Data.DataEjemplar.updateEjemplaresToAlquilados(DataEjemplar.java:282), utils.Test.main(Test.java:80)] Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''(4, 6)'' at line 1

feb. 04, 2024 5:47:03 P. M. utils.LoggerError log
SEVERE: Stack: [com.mysql.cj.jdbc.exceptions.SQLError.createSQLFeatureNotSupportedException(SQLError.java:236), com.mysql.cj.jdbc.ConnectionImpl.createArrayOf(ConnectionImpl.java:2638), Data.DataEjemplar.updateEjemplaresToAlquilados(DataEjemplar.java:281), utils.Test.main(Test.java:80)] Error: null

feb. 04, 2024 6:01:58 P. M. utils.LoggerError log
SEVERE: Stack: [java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64), java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70), java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266), java.base/java.util.Objects.checkIndex(Objects.java:359), java.base/java.util.ArrayList.get(ArrayList.java:427), Data.DataEjemplar.updateEjemplaresToAlquilados(DataEjemplar.java:289), utils.Test.main(Test.java:80)] Error: Index 2 out of bounds for length 2

